version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_METABASE_DB_NM}    
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge